# This configures Rubocop for this template repo - see
# [rubocop.yml.tt](./rubocop.yml.tt) if you want to change the Rubocop
# configuration which is copied into generated applications.
---
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  # Target the oldest Ruby that this template's chosen Rails version supports In
  # a normal Rails app, Rubocop would infer this from the version of Ruby
  # running. We want the rubocop checks that run on this repo to work for any
  # version of Ruby that the chosen Rails version supports so we have to be
  # explicit.
  TargetRubyVersion:
    <%=
    YAML.safe_load(Pathname.new("./target_versions.yml").realpath.read).fetch("minimum_ruby_major_minor")
    %>
  # In a normal Rails app, Rubocop would pull this from the Gemfile. We want the
  # rubocop checks that run on this repo to be consistent with the checks that
  # run on generated apps so we have to be explicit.
  TargetRailsVersion:
    <%=
    YAML.safe_load(Pathname.new("./target_versions.yml").realpath.read).fetch("target_rails_major_minor")
    %>
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: true # TODO: will be changed in v2 to 'false'

FactoryBot/SyntaxMethods:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument # TODO: will be changed in v2 to 'with_fixed_indentation'

Layout/CaseIndentation:
  EnforcedStyle: case # TODO: will be changed in v2 to 'end'

Layout/EmptyLineAfterGuardClause:
  Enabled: true # TODO: will be changed in v2 to 'false'

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword # TODO: will be changed in v2 to 'variable'

# We think that:
#   array = [
#     :value
#   ]
#   and_in_a_method_call([
#     :value
#   ])
# Looks better than:
#   value = [
#     :value
#   ]
#   but_in_a_method_call([
#                          :its_like_this
#                         ])
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent # TODO: will be changed in v2 to 'consistent'

# We think that:
#   hash = {
#     key: :value
#   }
#   and_in_a_method_call({
#     no: :difference
#   })
# Looks better than:
#   hash = {
#     key: :value
#   }
#   but_in_a_method_call({
#                          its_like: :this
#                         })
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent # TODO: will be changed in v2 to 'consistent'

Layout/LineLength:
  Max: 200

# We think that:
#     {
#       foo: :bar
#       baz: :bip
#     }
# Looks better than:
#     { foo: :bar
#       baz: :bip }
Layout/MultilineHashBraceLayout:
  Enabled: false

# We think that:
#    foo(
#      bar: :baz,
#      bip: :whizz
#    )
# Looks better than:
#    foo(bar: baz,
#        bip: :whizz)
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned # TODO: will be changed in v2 to 'indented'

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned # TODO: will be changed in v2 to 'indented'

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter # TODO: will be changed in v2 to 'with_fixed_indentation'

# This syntax is a deliberate idiom in rspec
# bbatsov endorses disabling it for rspec
# https://github.com/bbatsov/rubocop/issues/4222#issuecomment-290722962
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 18
  Exclude:
    - 'spec/**/*'
  Enabled: true # TODO: will be changed in v2 to 'false'

Metrics/BlockLength:
  Max: 50
  Enabled: true # TODO: will be changed in v2 to 'false'

Metrics/BlockNesting:
  Enabled: true # TODO: will be changed in v2 to 'false'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'
  Enabled: true # TODO: will be changed in v2 to 'false'

Metrics/CyclomaticComplexity:
  Max: 10
  Enabled: true # TODO: will be changed in v2 to 'false'

Metrics/MethodLength:
  Max: 50
  Enabled: true # TODO: will be changed in v2 to 'false'

Metrics/ModuleLength:
  Enabled: true # TODO: will be changed in v2 to 'false'

Metrics/ParameterLists:
  Enabled: true # TODO: will be changed in v2 to 'false'

Metrics/PerceivedComplexity:
  Enabled: true # TODO: will be changed in v2 to 'false'

Naming/FileName:
  Exclude:
    - '**/Gemfile.rb'
    - '**/Rakefile.rb'

Naming/HeredocDelimiterNaming:
  Enabled: true # TODO: will be changed in v2 to 'false'

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

# This cop complains when you have variables named things like:
#     address_line_1
#     address_line_2
# etc.
Naming/VariableNumber:
  Enabled: false # TODO: will be changed in v2 to 'false'

Performance/Casecmp:
  Enabled: false

RSpec:
  Language:
    Expectations:
      - assert_match

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/RepeatedExample:
  Exclude:
    - 'variants/pundit/spec/policies/**'

Rails:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/application_controller.rb'

# we don't require using Rails.logger in lib, as it often doesn't go where
# we'd want for the code that lives there, or otherwise isn't even available
Rails/Output:
  Exclude:
    - 'lib/**/*'

Rails/SquishedSQLHeredocs:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias # TODO: will be changed in v2 to 'prefer_alias_method'

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/BlockDelimiters:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/ClassAndModuleChildren:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/Documentation:
  Enabled: false # TODO: will be changed in v2 to 'false'

Style/DoubleNegation:
  Enabled: false # TODO: will be changed in v2 to 'false'

Style/EmptyMethod:
  Enabled: false
  EnforcedStyle: compact # TODO: will be changed in v2 to 'expanded'

Style/FormatString:
  Enabled: true # TODO: will be changed in v2 to 'false'

# Ruby supports two styles of string template formatting.
# "annotated" - format("%<greeting>s", greeting: "Hello")
# "template"  - format("%{greeting}", greeting: "Hello")
#
# While the annotated format is more descriptive, it also comes in a style that is
# significantly harder for a developer to parse. The template style is easy to read, understand,
# and is consistent with formatting with (for example), interpolation (#{}).
Style/FormatStringToken:
  EnforcedStyle: template
  Enabled: true # TODO: will be changed in v2 to 'false'

# Ruby 2.4+ has a magic comment that makes all strings frozen and Rubocop wants to put it
# at the top of every. single. file. We decided we didn't want that - for now.
Style/FrozenStringLiteralComment:
  Enabled: false # TODO: will be changed in v2 to 'false'

Style/GuardClause:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/HashSyntax:
  EnforcedShorthandSyntax: always

# https://rubocop.readthedocs.io/en/latest/cops_style/
Style/HashTransformKeys:
  Enabled: false

# https://rubocop.readthedocs.io/en/latest/cops_style/
Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/Lambda:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/ModuleFunction:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/NegatedIf:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/Next:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/NumericLiterals:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/NumericPredicate:
  Enabled: false # TODO: will be changed in v2 to 'false'

Style/ParallelAssignment:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/PerlBackrefs:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/RaiseArgs:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/RegexpLiteral:
  Enabled: true # TODO: will be changed in v2 to 'false'

Style/RescueStandardError:
  EnforcedStyle: explicit # TODO: will be changed in v2 to 'implicit'

# Disable preference for Ruby's new safe navigation operator `&.` because it
# usually comes at the cost of expressiveness in the simple case:
#
#     -      coupon_usage.destroy if coupon_usage
#     +      coupon_usage&.destroy
#
# And guides you towards Law of Demeter violations in the extreme case:
#
#     result&.data&.attributes&.payments&.first&.payment_token
#
# Disabling this cop doesn't stop you from using it, but be prepared to defend
# it in code review if you do.
Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  Enabled: true # TODO: will be changed in v2 to 'false'

# Single line method definitions are totally fine, and often more readable, consider:
#    class WidgetsPolicy
#      def create?; false; end
#      def index?;  true;  end
#      def show?;   true;  end
#      def update?; false; end
#      def delete?; false; end
#    end
Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: true # TODO: will be changed in v2 to 'false'

# Just always use double quotes and stop thinking about it.
Style/StringLiterals:
  EnforcedStyle: double_quotes # TODO: will be changed in v2 to 'double_quotes'

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes # TODO: will be changed in v2 to 'double_quotes'

Style/SymbolArray:
  EnforcedStyle: percent # TODO: will be changed in v2 to 'brackets'

Style/TernaryParentheses:
  EnforcedStyle: require_no_parentheses # TODO: will be changed in v2 to 'require_parentheses_when_complex'

Style/WordArray:
  EnforcedStyle: percent # TODO: will be changed in v2 to 'brackets'
