# This configures Rubocop for this template repo - see
# [rubocop.yml.tt](./rubocop.yml.tt) if you want to change the Rubocop
# configuration which is copied into generated applications.
---
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  # Target the oldest Ruby that this template's chosen Rails version supports In
  # a normal Rails app, Rubocop would infer this from the version of Ruby
  # running. We want the rubocop checks that run on this repo to work for any
  # version of Ruby that the chosen Rails version supports so we have to be
  # explicit.
  TargetRubyVersion:
    <%=
    YAML.safe_load(Pathname.new("./target_versions.yml").realpath.read).fetch("minimum_ruby_major_minor")
    %>
  # In a normal Rails app, Rubocop would pull this from the Gemfile. We want the
  # rubocop checks that run on this repo to be consistent with the checks that
  # run on generated apps so we have to be explicit.
  TargetRailsVersion:
    <%=
    YAML.safe_load(Pathname.new("./target_versions.yml").realpath.read).fetch("target_rails_major_minor")
    %>
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

FactoryBot/SyntaxMethods:
  Enabled: false

# We think that:
#   array = [
#     :value
#   ]
#   and_in_a_method_call([
#     :value
#   ])
# Looks better than:
#   value = [
#     :value
#   ]
#   but_in_a_method_call([
#                          :its_like_this
#                         ])
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# We think that:
#   hash = {
#     key: :value
#   }
#   and_in_a_method_call({
#     no: :difference
#   })
# Looks better than:
#   hash = {
#     key: :value
#   }
#   but_in_a_method_call({
#                          its_like: :this
#                         })
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 200

# We think that:
#     {
#       foo: :bar
#       baz: :bip
#     }
# Looks better than:
#     { foo: :bar
#       baz: :bip }
Layout/MultilineHashBraceLayout:
  Enabled: false

# We think that:
#    foo(
#      bar: :baz,
#      bip: :whizz
#    )
# Looks better than:
#    foo(bar: baz,
#        bip: :whizz)
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

# This syntax is a deliberate idiom in rspec
# bbatsov endorses disabling it for rspec
# https://github.com/bbatsov/rubocop/issues/4222#issuecomment-290722962
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 18
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Naming/FileName:
  Exclude:
    - '**/Gemfile.rb'
    - '**/Rakefile.rb'

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

# This cop complains when you have variables named things like:
#     address_line_1
#     address_line_2
# etc.
Naming/VariableNumber:
  Enabled: false

Performance/Casecmp:
  Enabled: false

RSpec:
  Language:
    Expectations:
      - assert_match

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/RepeatedExample:
  Exclude:
    - 'variants/pundit/spec/policies/**'

Rails:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/application_controller.rb'

# we don't require using Rails.logger in lib, as it often doesn't go where
# we'd want for the code that lives there, or otherwise isn't even available
Rails/Output:
  Exclude:
    - 'lib/**/*'

Rails/SquishedSQLHeredocs:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

# Ruby supports two styles of string template formatting.
# "annotated" - format("%<greeting>s", greeting: "Hello")
# "template"  - format("%{greeting}", greeting: "Hello")
#
# While the annotated format is more descriptive, it also comes in a style that is
# significantly harder for a developer to parse. The template style is easy to read, understand,
# and is consistent with formatting with (for example), interpolation (#{}).
Style/FormatStringToken:
  EnforcedStyle: template

# Ruby 2.4+ has a magic comment that makes all strings frozen and Rubocop wants to put it
# at the top of every. single. file. We decided we didn't want that - for now.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

# https://rubocop.readthedocs.io/en/latest/cops_style/
Style/HashTransformKeys:
  Enabled: false

# https://rubocop.readthedocs.io/en/latest/cops_style/
Style/HashTransformValues:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Disable preference for Ruby's new safe navigation operator `&.` because it
# usually comes at the cost of expressiveness in the simple case:
#
#     -      coupon_usage.destroy if coupon_usage
#     +      coupon_usage&.destroy
#
# And guides you towards Law of Demeter violations in the extreme case:
#
#     result&.data&.attributes&.payments&.first&.payment_token
#
# Disabling this cop doesn't stop you from using it, but be prepared to defend
# it in code review if you do.
Style/SafeNavigation:
  Enabled: false

# Single line method definitions are totally fine, and often more readable, consider:
#    class WidgetsPolicy
#      def create?; false; end
#      def index?;  true;  end
#      def show?;   true;  end
#      def update?; false; end
#      def delete?; false; end
#    end
Style/SingleLineMethods:
  Enabled: false

# Just always use double quotes and stop thinking about it.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
