language: ruby
services:
  - postgresql
before_script:
  - nvm install
env:
  # Generate the basic variant with options:
  #   - example.com (production hostname)
  #   - staging.example.com (staging hostname)
  #   - n (no, do not add foundation)
  #   - n (no, do not overwrite webpacker with rails version)
  - VARIANT=basic GENERATOR_INPUT="example.com\nstaging.example.com\nn\nn"
  # Generate the foundation variant with options:
  #   - example.com (production hostname)
  #   - staging.example.com (staging hostname)
  #   - Y (yes, add foundation)
  #   - n (no, don't add foundation layout)
  #   - n (no, do not overwrite webpacker with rails version)
  - VARIANT=foundation GENERATOR_INPUT="example.com\nstaging.example.com\nY\nn\nn"
  # Generate the foundation-layout variant with options:
  #   - example.com (production hostname)
  #   - staging.example.com (staging hostname)
  #   - Y (yes, add foundation)
  #   - Y (yes, add foundation layout)
  #   - n (no, do not overwrite webpacker with rails version)
  - VARIANT=foundation-layout GENERATOR_INPUT="example.com\nstaging.example.com\nY\nY\nY\nn"
script:
  - ./template-test/ci-run.sh
notifications:
  slack:
    if: branch = master
    on_success: change
    secure: sFji8Sh31tpZTuLnrqyhvm3M0HEoaTTY+RIXvvmfr6gZosPoHjQrJ7ITkuL5KueNg/p8jqW8j/FHBcbr6fYmILZu7j9EHijI6NUykhLNrU84bbxQRfvQzl3kj0/kxsXrpWSfhLSL9jBIZL2fGrWnS0cA6I3IgtA2lnWOXjYFjt4lbhy/JYIT2ACfpyhzZPDZBQhVm1ww7LPoOMmKFjmkKhS7ZMWcNbMRzoYHfK/HbJ0B+j5cw2U+V6wUdKLWDFbO7rln5mzlHqusfZw9S736D1cdlN6G29MN2y+6gk8I/GirzmNk7+CUImrRcK53wZ2gwc9COexJVskRS6LWCWsT9z55p2xze/RVD7EsQ9x39fbwSABQIMT2PNOvjo3pv8uOtfzckjqjUZa0gzkhhbrf6HFzG/7xRLXYFPImp6/55if26/E1y/MPvvKokZKMR1MU9kDrSNthqbFhF95Uot5P+thtAptHL1I9fArHSuevbSyhr4kZGN8XYhoXSkYKDgCBKJiECDBbSKyQ0qrfr55045IvjNWk7cGWj/+L5zLwqRnQoEOaln8c0ApYy+HhSp8s1Ni/OhLnLn8cdvAVfXooKPcZ+lmXzgAfk6qjkfO53fDawzrFnPFHgKSpIgTWGywMWrxr0YADO8fTRgI+V16vQTeawsqaC6JweqPJjYMYKfM=
