# This file contains the Travis build configuration for the README.
# Travis is configured to run builds against all branches and pull requests
# (the result of merging the branch into a local copy of 'master').
#
# Travis also supports scheduled builds. These cannot be configured in .travis.yml,
# but for the purposes of being clear, we **do** have a scheduled build set up to run
# once per month against 'master' only. This means that we can catch any problems
# with the template arising from library & framework updates before they affect a new project.
#
# To view the scheduled build configuration, check out: https://travis-ci.org/ackama/rails-template/settings
language: ruby
services:
  - postgresql
before_script:
  - nvm install
env:
  # Variant: basic
  # - 'example.com'          (Set production URL)
  # - 'staging.example.com'  (Set staging URL)
  # - 'No'                   (Install foundation?)
  # - 'No'                   (Install Sidekiq?)
  # - ''                     (Choose git remote URL)
  # - 'No'                   (Install devise?)
  - VARIANT=basic
    GENERATOR_INPUT="example.com\nstaging.example.com\nNo\nNo\n\nNo\n"

  # Variant: foundation
  # - 'example.com'          (Set production URL)
  # - 'staging.example.com'  (Set staging URL)
  # - 'Yes'                  (Install foundation?)
  # - 'No'                   (Install Sidekiq?)
  # - ''                     (Choose git remote URL)
  # - 'No'                   (Install devise?)
  - VARIANT=foundation
    GENERATOR_INPUT="example.com\nstaging.example.com\nYes\nNo\n\nNo\n"

  # Variant: foundation-layout
  # - 'example.com'          (Set production URL)
  # - 'staging.example.com'  (Set staging URL)
  # - 'Yes'                  (Install foundation?)
  # - 'Yes'                  (Install foundation-layout?)
  # - 'No'                   (Install Sidekiq?)
  # - ''                     (Choose git remote URL)
  # - 'No'                   (Install devise?)
  - VARIANT=foundation-layout
    GENERATOR_INPUT="example.com\nstaging.example.com\nYes\nYes\nNo\n\nNo\n"

  # Variant: sidekiq
  # - 'example.com'          (Set production URL)
  # - 'staging.example.com'  (Set staging URL)
  # - 'No'                   (Install foundation?)
  # - 'Yes'                  (Install Sidekiq?)
  # - ''                     (Choose git remote URL)
  # - 'No'                   (Install devise?)
  - VARIANT=sidekiq
    GENERATOR_INPUT="example.com\nstaging.example.com\nNo\nYes\n\nNo\n"

  # Variant: devise
  # - 'example.com'          (Set production URL)
  # - 'staging.example.com'  (Set staging URL)
  # - 'No'                   (Install foundation?)
  # - 'No'                   (Install Sidekiq?)
  # - ''                     (Choose git remote URL)
  # - 'Yes'                  (Install devise?)
  # - ''                     (Set devise email 'From:' address)
  # - 'Yes'                  (Should devise do git commit?)
  - VARIANT=devise
    GENERATOR_INPUT="example.com\nstaging.example.com\nNo\nNo\n\nYes\nYes\nNo\n"
script:
  - ./template-test/ci-run.sh
notifications:
  slack:
    if: branch = master
    on_success: change
    secure: sFji8Sh31tpZTuLnrqyhvm3M0HEoaTTY+RIXvvmfr6gZosPoHjQrJ7ITkuL5KueNg/p8jqW8j/FHBcbr6fYmILZu7j9EHijI6NUykhLNrU84bbxQRfvQzl3kj0/kxsXrpWSfhLSL9jBIZL2fGrWnS0cA6I3IgtA2lnWOXjYFjt4lbhy/JYIT2ACfpyhzZPDZBQhVm1ww7LPoOMmKFjmkKhS7ZMWcNbMRzoYHfK/HbJ0B+j5cw2U+V6wUdKLWDFbO7rln5mzlHqusfZw9S736D1cdlN6G29MN2y+6gk8I/GirzmNk7+CUImrRcK53wZ2gwc9COexJVskRS6LWCWsT9z55p2xze/RVD7EsQ9x39fbwSABQIMT2PNOvjo3pv8uOtfzckjqjUZa0gzkhhbrf6HFzG/7xRLXYFPImp6/55if26/E1y/MPvvKokZKMR1MU9kDrSNthqbFhF95Uot5P+thtAptHL1I9fArHSuevbSyhr4kZGN8XYhoXSkYKDgCBKJiECDBbSKyQ0qrfr55045IvjNWk7cGWj/+L5zLwqRnQoEOaln8c0ApYy+HhSp8s1Ni/OhLnLn8cdvAVfXooKPcZ+lmXzgAfk6qjkfO53fDawzrFnPFHgKSpIgTWGywMWrxr0YADO8fTRgI+V16vQTeawsqaC6JweqPJjYMYKfM=
