# This file contains the Travis build configuration for the README.
# Travis is configured to run builds against all branches and pull requests
# (the result of merging the branch into a local copy of 'master').
#
# Travis also supports scheduled builds. These cannot be configured in .travis.yml,
# but for the purposes of being clear, we **do** have a scheduled build set up to run
# once per month against 'master' only. This means that we can catch any problems
# with the template arising from library & framework updates before they affect a new project.
# 
# To view the scheduled build configuration, check out: https://travis-ci.org/ackama/rails-template/settings
language: ruby
services:
  - postgresql
before_script:
  - nvm install
env:
  # Generate the basic variant with options:
  #   - example.com (production hostname)
  #   - staging.example.com (staging hostname)
  #   - n (no, do not add foundation)
  #   - n (no, do not overwrite webpacker with rails version)
  - VARIANT=basic GENERATOR_INPUT="example.com\nstaging.example.com\nn\nn"
  # Generate the foundation variant with options:
  #   - example.com (production hostname)
  #   - staging.example.com (staging hostname)
  #   - Y (yes, add foundation)
  #   - n (no, don't add foundation layout)
  #   - n (no, do not overwrite webpacker with rails version)
  - VARIANT=foundation GENERATOR_INPUT="example.com\nstaging.example.com\nY\nn\nn"
  # Generate the foundation-layout variant with options:
  #   - example.com (production hostname)
  #   - staging.example.com (staging hostname)
  #   - Y (yes, add foundation)
  #   - Y (yes, add foundation layout)
  #   - n (no, do not overwrite webpacker with rails version)
  - VARIANT=foundation-layout GENERATOR_INPUT="example.com\nstaging.example.com\nY\nY\nY\nn"
script:
  - ./template-test/ci-run.sh
