---
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
EnableDefaultLinters: true
linters:
  RequireScriptNonce:
    enabled: true
  PartialInstanceVariable:
    enabled: true
  HardCodedString:
    enabled: false
  ErbSafety:
    enabled: true
  SpaceInHtmlTag:
    enabled: false
  NoJavascriptTagHelper:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Rails/OutputSafety:
        # Disable this because erb-lint already checks this
        Enabled: false
