# Be sure to restart your server when you modify this file.
#
# Use this file to load non-sensitive app config from ENV. Config values here
# will be loaded into `Rails.application.config.app`.
#
# Sensitive config should be put in `config/secrets.yml` (which will load it
# into `Rails.application.secrets`)

default:
  &default # The default `From:` address to use for email sent by this application
  mail_from: "<%= ENV['MAIL_FROM'] %>"

  # this should either begin with GTM- (for a container) or G- (for a tag)
  google_analytics_id: "<%= ENV.fetch('GOOGLE_ANALYTICS_ID', nil) %>"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
