# Be sure to restart your server when you modify this file.
#
# Use this file to load non-sensitive app config from ENV. Config values here
# will be loaded into `Rails.application.config.app`.
#
# Sensitive config should be put in `config/secrets.yml` (which will load it
# into `Rails.application.secrets`)

default:
  &default # The default `From:` address to use for email sent by this application
  mail_from: "<%= ENV['MAIL_FROM'] %>"

  active_record_encryption_primary_key:
    "<%= ENV.fetch('ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY') %>"
  active_record_encryption_deterministic_key:
    "<%= ENV.fetch('ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY') %>"
  active_record_encryption_key_derivation_salt:
    "<%= ENV.fetch('ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT') %>"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
