# Be sure to restart your server when you modify this file.
#
# Use this file to load configuration values from the environment, which will
# be accessible by the app through `Rails.application.config.app`

default: &default
  # Your secret key is used for verifying the integrity of signed cookies.
  # If you change this key, all old signed cookies will become invalid!
  # Make sure the secret is at least 30 characters and all random,
  # no regular words, or you'll be exposed to dictionary attacks.
  # You can use `rails secret` to generate a secure secret key.
  secret_key_base: "<%= ENV.fetch('RAILS_SECRET_KEY_BASE') %>"

  # The default `From:` address to use for email sent by this application
  mail_from: "<%= ENV['MAIL_FROM'] %>"

  active_record_encryption_primary_key:
    "<%= ENV.fetch('ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY') %>"
  active_record_encryption_deterministic_key:
    "<%= ENV.fetch('ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY') %>"
  active_record_encryption_key_derivation_salt:
    "<%= ENV.fetch('ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT') %>"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
