# Sensitive app config values from ENV should be loaded in this file.
#
# Do NOT put secrets **directly** into this file. All secrets should be loaded
# from ENV!  Be sure to restart your server when you modify this file.

default: &default

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
