name: Rails Template CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # * At 05:00 UTC every Monday, run the latest commit on the default or base branch
    - cron:  '0 5 * * MON'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # don't stop all variants if one of them fails (we usually want to know
      # how many fail)
      fail-fast: false
      matrix:
        variant:
          - name: basic
            config_path: "ci/configs/basic.yml"
            skips: --skip-javascript
          - name: react
            config_path: "ci/configs/react.yml"
            skips: --skip-javascript
          - name: typescript
            config_path: "ci/configs/typescript.yml"
            skips: --skip-javascript
          - name: sidekiq
            config_path: "ci/configs/sidekiq.yml"
            skips: --skip-javascript
          - name: devise
            config_path: "ci/configs/devise.yml"
            skips: --skip-javascript
          - name: devise_2fa
            config_path: "ci/configs/devise_2fa.yml"
            skips: --skip-javascript
          - name: basic_with_skips
            config_path: "ci/configs/basic.yml"
            skips: --skip-active-storage --skip-spring --skip-javascript
    services:
      db:
        image: postgres
        env:
          # The Postgres service fails its docker health check unless you
          # specify these environment variables
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: anything # can be anything, is ignored by the tests
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # We don't cache gems or JS packages because we are actually testing how
      # installation and setup works in this project so, while caching would
      # make CI faster, it might hide problems.

      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.0'

      - name: Setup git for committing
        run: |
          # We do some git commits during our testing so these need to be set
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Run CI script
        env:
          # Remember that your app name becomes a top-level constant in the
          # Rails app so you'll run into issues if that constant shares a name
          # with a class provided by a gem. Basically, don't name your app
          # "react", "sidekiq" etc.
          APP_NAME: ${{ matrix.variant.name }}demo
          CONFIG_PATH:  ${{ matrix.variant.config_path }}
          SKIPS: ${{ matrix.variant.skips }}
          PGUSER: postgres
          PGPASSWORD: postgres
          PGHOST: localhost
        run: ./ci/bin/build-and-test
